"""add unique constraint to names in author, publisher, and category

Revision ID: 999e103be947
Revises: f938b0d91f25
Create Date: 2026-02-19 15:01:55.418528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999e103be947'
down_revision: Union[str, Sequence[str], None] = 'f938b0d91f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['name'])
    op.create_unique_constraint(None, 'categories', ['name'])
    op.alter_column('fines', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2, asdecimal=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'publishers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publishers', type_='unique')
    op.alter_column('fines', 'amount',
               existing_type=sa.Float(precision=2, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
